.deploy_template: &deploy_definition
  dependencies: []
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - ssh -p22 root@$CI_ENVIRONMENT_URL "docker pull $PULL_REPO"
    - ssh -p22 root@$CI_ENVIRONMENT_URL "docker stop $REPO_NAME-$CI_ENVIRONMENT_NAME || true"
    - ssh -p22 root@$CI_ENVIRONMENT_URL "docker rm -f $REPO_NAME-$CI_ENVIRONMENT_NAME || true"
    - ssh -p22 root@$CI_ENVIRONMENT_URL "docker run -d --restart=always -p $BIND_ADDRESS:9001 --name $REPO_NAME-$CI_ENVIRONMENT_NAME --env=MAX_MEMORY=$MAX_MEMORY --env=MEMORY_NEW_RATIO=$MEMORY_NEW_RATIO --log-driver=syslog -v /root/$REPO_NAME-$CI_ENVIRONMENT_NAME/log4j2-spring.xml:/usr/src/app/log4j2-spring.xml -v /root/$REPO_NAME-$CI_ENVIRONMENT_NAME/logs:/usr/src/logs -v /root/$REPO_NAME-$CI_ENVIRONMENT_NAME/application-prod.properties:/usr/src/app/application-prod.properties $PULL_REPO"

stages:
  - package
  - build
  - deploy_test
  - deploy_preprod
  - deploy_prod

variables:
  REPO_NAME: annotation-service
  PULL_REPO: registry-vpc.cn-hangzhou.aliyuncs.com/malgo/$REPO_NAME:$CI_COMMIT_SHA
  PUSH_REPO: $REGISTRY_SERVER/malgo/$REPO_NAME:$CI_COMMIT_SHA
  MAVEN_CLI_OPTS: "-s /gitlab/.m2/settings.xml --batch-mode -U"
  MAVEN_OPTS: "-Dmaven.repo.local=/gitlab/.m2/repository"

maven-build:
  image: maven:3-jdk-8
  stage: package
  tags:
    - backend
  script:
    - mvn $MAVEN_CLI_OPTS package
    - mvn $MAVEN_CLI_OPTS org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -Doutput=./target/.version
  artifacts:
    expire_in: 1h
    paths:
      - target/*.jar
      - target/.version
  only:
    - develop
    - release
    - hotfix
    - master
    - /^feature\/.*$/

docker-build:
  stage: build
  image: docker:latest
  tags:
    - dind
  allow_failure: false
  before_script:
    - docker info
  script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY_SERVER
    - docker build -t $PUSH_REPO --build-arg JAR_FILE=$REPO_NAME-`cat ./target/.version`.jar -f APP-META/Dockerfile .
    - docker push $PUSH_REPO
  only:
    - develop
    - release
    - /^hotfix\-[0-9]+$/
    - master
    - /^feature\/.*$/

#deploy-test:
#  stage: deploy_test
#  tags:
#    - deploy
#  environment:
#    name: test
#    url: 121.196.212.109
#  when: on_success
#  only:
#    - develop
#  variables:
#    GIT_STRATEGY: none
#    BIND_ADDRESS: 172.16.209.199:9002
#    MAX_MEMORY: 768m
#    MEMORY_NEW_RATIO: 4
#  <<: *deploy_definition

deploy-test:
  stage: deploy_test
  tags:
    - deploy
  environment:
    name: test
    url: 118.31.10.105
  only:
    - develop
    - /^feature\/.*$/
  variables:
    GIT_STRATEGY: none
    BIND_ADDRESS: 172.16.209.197:9021
    MAX_MEMORY: 1024m
    MEMORY_NEW_RATIO: 3
  <<: *deploy_definition

deploy-preprod:
  stage: deploy_preprod
  tags:
    - deploy
  environment:
    name: preprod
    url: 118.31.10.105
  when: manual
  only:
    - master
    - relesae
    - /^hotfix\-[0-9]+$/
  variables:
    GIT_STRATEGY: none
    BIND_ADDRESS: 172.16.209.197:9022
    MAX_MEMORY: 4096m
    MEMORY_NEW_RATIO: 3
  <<: *deploy_definition

deploy-prod:
  stage: deploy_prod
  tags:
    - deploy
  environment:
    name: prod
    url: 118.31.10.105
  when: manual
  only:
    - master
  variables:
    GIT_STRATEGY: none
    BIND_ADDRESS: 172.16.209.197:9023
    MAX_MEMORY: 4096m
    MEMORY_NEW_RATIO: 3
  <<: *deploy_definition
